const Action={
    ADD_TODO:'ADD_TODO',
    DELETE_TASK:'DELETE_TASK',
    CHECKED_TASK:'CHECKED_TASK',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    AUTH_INITIATE:'AUTH_INITIATE',
    LOG_OUT:'LOG_OUT'
    

}
export default Action